apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: reverse-words
spec:
  host: reversewords-rishav-dev.appdev-cloudnative-ocp43-6fb0b86391cd68c8282858623a1dddff-0000.eu-gb.containers.appdomain.cloud
  port:
    targetPort: http
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: reverse-words
    weight: 100
status:
  ingress: []
